nav:
  

site_name: e路有我
theme:
  icon:
    repo: fontawesome/brands/git-alt
  name: material
  palette:
    scheme: slate
    primary: deep purple
  font:
    code: Roboto Mono
  features:
    - navigation.tabs
    - header.autohide
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hxaxd/elyw
repo_url: https://github.com/hxaxd/elyw
repo_name: e路有我