nav:
  - 目录: index.md
  - Windows 系统环境配置:
    - Windows 系统使用: 通识/Windows系统使用.md
    - 浏览器使用: 通识/浏览器使用.md
    - Windows 系统上的软件: 通识/Windows系统上的软件.md
  - 编程与编程语言:
    - 编程语言杂谈: 通识/编程语言杂谈.md
    - 编程实现原理: 通识/编程实现原理.md
    - C 语言: 通识/C语言.md
    - C 中的内存: 通识/C中的内存.md
    - 面向对象: 通识/面向对象.md
    - C++ 语言: 通识/C++语言.md
  - 开发环境配置:
    - 开发环境概念: 通识/开发环境概念.md
    - 开发环境配置: 通识/开发环境配置.md
    - 环境配置杂谈: 通识/环境配置杂谈.md
  - Python 与编程工程化:
    - Python 语言: 通识/Python语言.md
    - Python 环境配置: 通识/Python环境配置.md
    - 包管理: 通识/包管理.md
    - 框架: 通识/框架.md
  - 面向 AI 编程:
    - 配置 AI: 通识/配置AI.md
    - 解决问题: 通识/解决问题.md
  - 通识杂言:
    - 容器: 通识/容器.md
    - 竞赛: 通识/竞赛.md

#  - 计算机科学:
#    - 计算机科学概论: 科学/计算机科学概论.md
#    - 函数式编程: 科学/函数式编程.md
#    - 计算理论: 科学/计算理论.md
#  - 数学:
#    - 数学基础: 科学/数学基础.md
#    - 线性代数: 科学/线性代数.md
#    - 概率论: 科学/概率论.md
#    - 离散数学: 科学/离散数学.md
#    - 抽象代数: 科学/抽象代数.md
#
#  - 软件开发:
#    - 就业: 开发/就业.md
#    - WEB 开发: 开发/WEB开发.md
#  - 前端技术:
#    - 前端基础: 开发/前端基础.md
#    - 框架: 开发/框架.md
#  - 后端技术:
#    - 后端基础: 开发/后端基础.md
#    - 框架: 开发/框架.md
#    - 数据库: 开发/数据库.md
#    - 架构: 开发/架构.md
#  - 测试与部署:
#    - 测试: 开发/测试.md
#    - 部署: 开发/部署.md
#
#  - 算法:
#    - 算法基础: 算法/算法基础.md
#    - 就业中的算法: 算法/就业中的算法.md
#    - 竞赛中的算法: 算法/竞赛中的算法.md  
#
#  - Linux 系统:
#    - Linux 系统: Linux/Linux系统.md
#    - Shell: Linux/Shell.md
#    - Shell 上的软件: Linux/Shell上的软件.md
#    - 管理 Linux: Linux/管理Linux.md


site_name: e路有我
theme:
  icon:
    repo: fontawesome/brands/git-alt
  name: material
  palette:
    scheme: slate
    primary: deep purple
  font:
    code: Roboto Mono
  features:
    - navigation.tabs
    - header.autohide
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hxaxd/elyw
repo_url: https://github.com/hxaxd/elyw
repo_name: e路有我